import { EventEmitter } from 'events';
import type { Finding } from '@guardiant/shared';

/**
 * Events emitted by streaming report generation
 */
export interface ReportStreamEvents {
  'finding': (finding: Finding, index: number, total: number) => void;
  'section': (section: string) => void;
  'progress': (percent: number) => void;
  'done': (reportPath?: string) => void;
  'error': (err: Error) => void;
}

/**
 * A typed EventEmitter that streams report output one finding at a time.
 * Useful for large scans (100+ findings) where writing the full JSON/Markdown
 * to memory first would cause high peak RSS.
 *
 * Usage:
 *   const stream = new ReportStream(findings, { format: 'markdown' });
 *   stream.on('finding', (f, i, total) => process.stdout.write(renderFinding(f)));
 *   stream.on('done', () => console.log('Report complete'));
 *   stream.start();
 */
export class ReportStream extends EventEmitter {
  private findings: Finding[];
  private format: 'json' | 'markdown' | 'html';
  private chunkMs: number;

  constructor(
    findings: Finding[],
    options: { format?: 'json' | 'markdown' | 'html'; chunkMs?: number } = {}
  ) {
    super();
    this.findings = findings;
    this.format = options.format ?? 'markdown';
    this.chunkMs = options.chunkMs ?? 0; // 0 = as fast as possible
  }

  /**
   * Begin streaming the report. Emits events asynchronously per-finding.
   */
  async start(): Promise<void> {
    const total = this.findings.length;

    try {
      // Emit header section
      this.emit('section', this.renderHeader(total));
      this.emit('progress', 0);

      for (let i = 0; i < total; i++) {
        const finding = this.findings[i];

        // Yield to event loop to allow consumers to process events
        if (this.chunkMs > 0) {
          await new Promise<void>((resolve) => setTimeout(resolve, this.chunkMs));
        } else {
          await new Promise<void>((resolve) => setImmediate(resolve));
        }

        this.emit('finding', finding, i + 1, total);
        this.emit('progress', Math.round(((i + 1) / total) * 100));
      }

      // Emit footer section
      this.emit('section', this.renderFooter(total));
      this.emit('done');
    } catch (err) {
      this.emit('error', err instanceof Error ? err : new Error(String(err)));
    }
  }

  private renderHeader(total: number): string {
    if (this.format === 'markdown') {
      return `# Guardiant Security Report\n\n> ${total} finding(s) follow.\n\n---\n`;
    }
    if (this.format === 'html') {
      return `<!DOCTYPE html><html><body><h1>Guardiant Report</h1><p>${total} findings</p>`;
    }
    return `{"findings":[`; // JSON opening
  }

  private renderFooter(total: number): string {
    if (this.format === 'json') {
      return `],"total":${total}}`;
    }
    if (this.format === 'html') {
      return `</body></html>`;
    }
    return `\n---\n*Report generated by Guardiant v0.1.0*\n`;
  }
}
